[tasks.rust-antora]
description = "Build Antora site and copy rust_docs"
script = [
  "cargo doc --target-dir docs/modules/ROOT/pages/rust_docs --no-deps --locked",
  "cd docs",
  "npx antora antora-playbook.yml",
  "bash ../scripts/rust_antora.sh"
]
