[default.extend-identifiers]
HashiCorp = "HashiCorp"
NOOPs = "NOOPs"

[default.extend-words]
# Technical term for "no operation" transactions
NOOP = "NOOP"
noop = "noop"

[default]
# Ignore short and long SHA commit hashes (7-40 hex characters)
extend-ignore-identifiers-re = [
    "[a-f0-9]{7,40}",
]
