= API Reference
:description: API reference document, including usage examples

This document provides information on the implemented API, along with usage examples. 

== Pre-requisites
. API key
This key is essential for most API calls. It can be set in `.env` file, under the `API_KEY` variable.
In case of a change on the key, there is no need to rebuild docker images, as `docker compose` will pick up the changes the next time the container is started.

This key should be sent as a header for most of the API calls:

[source,json]
----
x-api-key: <my api key>
----

== Request format
By default, the container listens on port `8080`. Calls should follow call the URL:
`http://<server_address_or_IP>:8080/api/v1/relayers/<relayer_name>/rpc`

NOTE: `relayer_name` is the name given to a relayer configuration in `./config/config.json` file.

The payload should follow the format:
[source,json]
----
{
  "jsonrpc": "2.0",
  "id": <id>,
  "method": "<method_name>",
  "params": { 
    <parameter_list>
  }
} 
----

Where:
- `method_name` - method to invoke. Please check sections bellow for available methods
- `id` - unique id, used to correlate request to response
- `parameter_list` - list of parameters required by chosen method

== Environments
- Solana
- EVM

== API Reference
* xref:common_actions[Common Actions]
* xref:solana_api[Solana]
* xref:evm_api[EVM]

[#common_actions]
=== Common actions
These are a set of REST calls common to both Solana and EVM relayers.

NOTE: We are assuming a base url of `http://localhost:8080/` for these examples.

- List relayers

Request: `GET http://localhost:8080/api/v1/relayers/`

Example request:
[source,bash]
----
curl --location --request GET 'http://localhost:8080/api/v1/relayers/' \
--header 'x-api-key: <my_api_key>'
----

Example response:
[source,json]
----
{
    "success": true,
    "data": [
        {
            "id": "sepolia-example",
            "name": "Sepolia Example",
            "network": "sepolia",
            "paused": false,
            "network_type": "evm",
            "signer_id": "local-signer",
            "policies": {
                "Evm": {
                    "gas_price_cap": null,
                    "whitelist_receivers": null,
                    "eip1559_pricing": false,
                    "private_transactions": false,
                    "min_balance": 1
                }
            },
            "address": "0xc834dcdc9a074dbbadcc71584789ae4b463db116",
            "notification_id": "notification-example",
            "system_disabled": false
        }
    ],
    "error": null,
    "pagination": {
        "current_page": 1,
        "per_page": 10,
        "total_items": 1
    }
}
----

- Get relayer details

Request: `GET http://localhost:8080/api/v1/relayers/<relayer_id>`

* `relayer_id` can be found by listing relayers or checking the config file (`./config/config.json`)

Example request:
[source,bash]
----
curl --location --request GET 'http://localhost:8080/api/v1/relayers/<relayer_id>' \
--header 'x-api-key: <my_api_key>'
----

Example response:
[source,json]
----
{
    "success": true,
    "data": {
        "id": "sepolia-example",
        "name": "Sepolia Example",
        "network": "sepolia",
        "network_type": "evm",
        "paused": false,
        "policies": {
            "eip1559_pricing": false,
            "private_transactions": false,
            "min_balance": 1
        },
        "address": "0xc834dcdc9a074dbbadcc71584789ae4b463db116",
        "system_disabled": false
    },
    "error": null
}
----

- Update Relayer

Request: `PATCH http://localhost:8080/api/v1/relayers/<relayer_id>`

Example requesti to pause a relayer:
[source,bash]
----
curl --location --request PATCH 'http://localhost:8080/api/v1/relayers/<relayer_id>' \
--header 'x-api-key: <my_api_key>' \
--header 'Content-Type: application/json' \
--data-raw '{
    "paused": true
}'
----

Example response:
[source,json]
----
{
    "success": true,
    "data": {
        "id": "sepolia-example",
        "name": "Sepolia Example",
        "network": "sepolia",
        "paused": true,
        "network_type": "evm",
        "signer_id": "local-signer",
        "policies": {
            "Evm": {
                "gas_price_cap": null,
                "whitelist_receivers": null,
                "eip1559_pricing": false,
                "private_transactions": false,
                "min_balance": 1
            }
        },
        "address": "0xc834dcdc9a074dbbadcc71584789ae4b463db116",
        "notification_id": "notification-example",
        "system_disabled": false
    },
    "error": null
}
----

- Get relayer balance
Request: `GET http://localhost:8080/api/v1/relayers/<relayer_id>/balance`

[#solana_api]
=== Solana
Solana API
[cols="1,1,1,2"]
|===
|Method Name |Required Parameters |Result |Description

|feeEstimate
|`transaction`, `fee_token`
|`estimated_fee`, `conversion_rate`
|Estimate the fee for an arbitrary transaction using a specified token.

|transferTransaction
|`amount`, `token`, `source`, `destination`
|`transaction`, `fee_in_spl`, `token`, `fee_in_lamports`, `valid_until_blockheight`
|Create a transfer transaction for a specified token, sender, and recipient. The token supplied will be assumed to be the token to also be used for fees. Returns a partially signed transaction.

|prepareTransaction
|`transaction`, `fee_token`
|`transaction`, `fee_in_spl`, `fee_token`, `fee_in_lamports`, `valid_until_blockheight`
|Prepare a transaction by adding relayer-specific instructions. Returns a partially signed transaction.

|signTransaction
|`transaction`
|`transaction`, `signature`
|Sign a prepared transaction without submitting it to the blockchain.

|signAndSendTransaction
|`transaction`
|`transaction`, `signature`
|Sign and submit a transaction to the blockchain.

|getSupportedTokens
|(none)
|`tokens[]` (list of token metadata)
|Retrieve a list of tokens supported by the relayer for fee payments.

|getFeaturesEnabled
|(none)
|`features[]` (list of enabled features)
|Retrieve a list of features supported by the relayer.
|===

Key terminology
[cols="1,2"]
|===
|Key |Description

|`transaction`
|Base64-encoded serialized Solana transaction. This could be a signed or unsigned transaction.

|`signature`
|Unique “transaction hash” that can be used to look up transaction status on-chain.

|`source`
|Source wallet address. The relayer is responsible for deriving and the TA.

|`destination`
|Destination wallet address. The relayer is responsible for deriving and creating the TA if necessary.

|`fee_token`
|Token mint address for the fee payment.

|`fee_in_spl`
|Fee amount the end user will pay to the relayer to process the transaction in spl tokens in the smallest unit of the spl token (no decimals)

|`fee_in_lamports`
|Fee amount in Lamports the Relayer estimates it will pay for the transaction.

|`valid_until_block_height`
|Expiration block height for time-sensitive operations.

|`tokens[]`
|Array of supported token metadata (e.g., symbol, mint, decimals).

|`features[]`
|Array of features enabled by the relayer (e.g., bundle support, sponsorship).
|===

[#solana_api_examples]
==== Solana example calls

NOTE: We are assuming a base url of `http://localhost:8080/` for these examples.

* Get supported tokens
Request:
[source,bash]
----
curl --location --request POST 'http://localhost:8080/api/v1/relayers/<solana_relayer_id>/rpc' \
--header 'x-api-key: <my_api_key>' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "method": "getSupportedTokens",
    "params": {},
    "id": 2
}'
----

Result:
[source,json]
----
{
    "jsonrpc": "2.0",
    "result": {
        "tokens": [
            {
                "conversion_slippage_percentage": null,
                "decimals": 6,
                "max_allowed_fee": 100000000,
                "mint": "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
                "symbol": "USDC"
            },
            {
                "conversion_slippage_percentage": null,
                "decimals": 9,
                "max_allowed_fee": null,
                "mint": "So11111111111111111111111111111111111111112",
                "symbol": "SOL"
            }
        ]
    },
    "id": 2
}
----

* Fee estimate
Request:
[source,bash]
----
curl --location --request POST 'http://localhost:8080/api/v1/relayers/<solana_relayer_id>/rpc' \
--header 'x-api-key: <my_api_key>' \
--header 'Content-Type: application/json' \
--data-raw '
{
  "jsonrpc": "2.0",
  "method": "feeEstimate",
  "params": {
    "transaction": "AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAEDpNhTBS0w2fqEkg0sAghld4KIZNFW3kt5Co2TA75icpEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZzDKeiaRTZZ3ipAtgJOOmqCGhz1iUHo8A9xynrbleugBAgIAAQwCAAAAQEIPAAAAAAA=",
    "fee_token": "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
  },
  "id": 3
}'
----

Result:
[source,json]
----
{
    "jsonrpc": "2.0",
    "result": {
        "conversion_rate": "142.6",
        "estimated_fee": "0.000713"
    },
    "id": 3
}
----

* Sign transaction
[source,bash]
----
curl --location --request POST 'http://localhost:8080/api/v1/relayers/<solana_relayer_id>/rpc' \
--header 'x-api-key: <my_api_key>' \
--header 'Content-Type: application/json' \
--data-raw '{
  "jsonrpc": "2.0",
  "method": "signTransaction",
  "params": {
    "transaction": "AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAEDpNhTBS0w2fqEkg0sAghld4KIZNFW3kt5Co2TA75icpEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/bKmYrYtPWWI7zwiXWqAC5iFnkAkRL2D8s6lPkoJJokBAgIAAQwCAAAAQEIPAAAAAAA="
    
  },
  "id": 4
}'
----

Result:
[source,json]
----
{
    "jsonrpc": "2.0",
    "result": {
        "signature": "2jg9xbGLtZRsiJBrDWQnz33JuLjDkiKSZuxZPdjJ3qrJbMeTEerXFAKynkPW63J88nq63cvosDNRsg9VqHtGixvP",
        "transaction": "AVbRgFoUlj0XdlLP4gJJ2zwmr/2g2LOdeNqGPYTl4VFzY7lrX+nKNXUEU0DLJEA+2BW3uHvudQSXz5YBqd5d9gwBAAEDpNhTBS0w2fqEkg0sAghld4KIZNFW3kt5Co2TA75icpEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/bKmYrYtPWWI7zwiXWqAC5iFnkAkRL2D8s6lPkoJJokBAgIAAQwCAAAAQEIPAAAAAAA="
    },
    "id": 4
}
----

* Sign and send transaction
[source,bash]
----
curl --location --request POST 'http://localhost:8080/api/v1/relayers/<solana_relayer_id>/rpc' \
--header 'x-api-key: <my_api_key>' \
--header 'Content-Type: application/json' \
--data-raw '{
  "jsonrpc": "2.0",
  "method": "signAndSendTransaction",
  "params": {
    "transaction": "AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAEDpNhTBS0w2fqEkg0sAghld4KIZNFW3kt5Co2TA75icpEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/bKmYrYtPWWI7zwiXWqAC5iFnkAkRL2D8s6lPkoJJokBAgIAAQwCAAAAQEIPAAAAAAA="
    
  },
  "id": 5
}'
----

Result:
[source,json]
----
{
    "jsonrpc": "2.0",
    "result": {
        "signature": "2jg9xbGLtZRsiJBrDWQnz33JuLjDkiKSZuxZPdjJ3qrJbMeTEerXFAKynkPW63J88nq63cvosDNRsg9VqHtGixvP",
        "transaction": "AVbRgFoUlj0XdlLP4gJJ2zwmr/2g2LOdeNqGPYTl4VFzY7lrX+nKNXUEU0DLJEA+2BW3uHvudQSXz5YBqd5d9gwBAAEDpNhTBS0w2fqEkg0sAghld4KIZNFW3kt5Co2TA75icpEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/bKmYrYtPWWI7zwiXWqAC5iFnkAkRL2D8s6lPkoJJokBAgIAAQwCAAAAQEIPAAAAAAA="
    },
    "id": 5
}
----

[#evm_api]
=== EVM

[#evm_api_examples]
==== EVM example calls


