:relayer: https://github.com/OpenZeppelin/openzeppelin-relayer

= OpenZeppelin Relayer
:description: User guide for setting up and configuring OpenZeppelin Relayer.

CAUTION: This software is in alpha stage. Use in production environments at your own risk.

OpenZeppelin Relayer is a service that provides infrastructure to relay transactions to the EVM & Non-EVM networks. It is designed to be used as a backend for dApps that need to interact with these networks.

**Features**

- **Multi-Chain Support**: Interact with multiple blockchain networks, including Solana and EVM-based chains.
- **Transaction Relaying**: Submit transactions to supported blockchain networks efficiently.
- **Transaction Signing**: Securely sign transactions using configurable key management.
- **Transaction Fee Estimation**: Estimate transaction fees for better cost management.
- **Solana Gasless Transactions**: Support for gasless transactions on Solana, enabling users to interact without transaction fees.
- **Transaction Nonce Management**: Handle nonce management to ensure transaction order.
- **Transaction Status Monitoring**: Track the status of submitted transactions.
- **Extensible Architecture**: Easily add support for new blockchain networks.
- **Configurable Network Policies**: Define and enforce network-specific policies for transaction processing.
- **Metrics and Observability**: Monitor application performance using Prometheus and Grafana.
- **Docker Support**: Deploy the relayer using Docker for both development and production environments.

**Supported Networks**

- Solana
- EVM (Basic support for Ethereum)

[NOTE]
====
To get started immediately, see xref:quickstart.adoc[Quickstart].
====

== Project Structure

The project follows a standard Rust project layout:


* `src/`: Source code
** `api/`: Route and controllers logic
** `config/`: Configuration logic
** `constants/`: Constant values used in the system
** `domain/`: Domain logic
** `init/`: Service initialization logic
** `jobs/`: Asynchronous processing logic (queueing)
** `logging/`: Logs and file rotation logic
** `metrics/`: Metrics logic
** `models/`: Data structures and types
** `repositories/`: Configuration storage
** `services/`: Services logic
** `utils/`: Helper functions
* `config/`: Configuration files
* `tests/`: Integration tests
* `docs/`: Documentation
* `scripts/`: Utility scripts
* `examples/`: Configuration examples
* `helpers/`: Rust helper scripts




For detailed information about each directory and its contents, see xref:structure.adoc[Project Structure Details].

== Getting Started

=== Prerequisites

* Rust 2021 edition
* Docker (optional, for containerized deployment)

=== Installation

==== Local Setup

. Clone the repository:

[source,bash]
----
git clone https://github.com/openzeppelin/openzeppelin-relayer
cd openzeppelin-relayer
----

. Install dependencies:

[source,bash]
----
cargo build
----

== Running the Relayer

=== Local Execution


[source,bash]
----
cargo run
----

NOTE: Before executing the command, ensure that the `.env` and `config.json` files are configured as detailed in the xref:index.adoc#configuration_references[Configuration References] section.

=== Docker Deployment

The Relayer can be run as either a development or production container using the corresponding Dockerfile (`Dockerfile.development` or `Dockerfile.production`).

==== Environment Configuration

* Edit `.env` at the root of the repository to adjust environment variables
* The appropriate .env file will be included during image build

==== Building the Image

You can build using Docker Compose (v2).

[source,bash]
----
# Default build
docker compose build

# Or, for a leaner image (and using Dockerfile.production)
DOCKERFILE=Dockerfile.production docker compose build
----

==== Running the Container

Use Docker Compose to run the container:

[source,bash]
----
docker compose up -d
----

For production runs, you can use:

[source,bash]
----
DOCKERFILE=Dockerfile.production docker compose up -d
----

== Configuration References

Most configuration files should live under `./config`, including the signer configurations, under `./config/keys`.
Please ensure appropriate access permissions on all configuration files (for `./config/keys/*`, we recommend `0500`.

=== Environment configuration (.env)

This file is the exception and should live in the same directory as `docker-compose.yaml`. It defines some base configurations for the Relayer application:
[source,json]
----
# For defaults see: ./docker-compose.yml
# Create a .env file in the root of the project and add your environment variables there
RUST_LOG=debug
CONFIG_FILE_PATH=./config/config.json
WEBHOOK_SIGNING_KEY=<my webhook signing key>
API_KEY=<my api key>
RATE_LIMIT_RPS=10
RATE_LIMIT_BURST_SIZE=10
METRICS_ENABLED=true
----

Make sure to, at least, choose your API key. Without it, you won't be able to interact with most of the API endpoints on the Relayer.
If you change any of these value, you will need to restart the container to make them active.

=== Main configuration file (config.json)

This file should exist in `config/config.json`

There are 3 important sections in this file:

* `signers` array, which must contain, at least, one valid signer configuration:
[source,json]
----
"signers": [
  {
    "id": "my_id",
    "type": "local",
    "path": "config/keys/local-signer.json",
    "passphrase": {
      "type": "plain",
      "value": "test"
    }
  }
]
----

Available configuration fields
[cols="1,1,2"]
|===
|Field |Type |Description

|id
|String
|Unique id for the signer

|type
|String
|Type of signer (see `supported signer types`)

|path
|String
|path to the signer json file. Should be under the `./config` directory

|passphrase.type
|String
|Type of passphrase (`env` or `plain`)

|passphrase.value
|String
|Passphrase value, env variable name, ...
|===


* `notifications` array, which should contain, at least, one valid configuration:
[source,json]
----
"notifications": [
  {
    "id": "notification-test",
    "type": "webhook",
    "url": "https://webhook.site/f95cf78d-742d-4b21-88b7-d683e6fd147b",
    "signing_key": {
      "type": "env",
      "name": "WEBHOOK_SIGNING_KEY"
    }
  }
]
----
Available configuration fields
[cols="1,1,2"]
|===
|Field |Type |Description

|id
|String
|Unique id for the notification

|type
|String
|Type of notification (only `webhook` available, for now)

|url
|String
|Notification URL

|signing_key.type
|String
|Type of key used in signing the notification (`env` or `plain`)

|signing_key.name
|String
|Signing key value, env variable name, ...
|===

* `relayers` array, containing at least one valid relayer configuration:
[source,json]
----
"relayers": [
  {
    "id": "solana-testnet",
    "name": "Solana Testnet",
    "paused": false,
    "notification_id": "notification-test",
    "signer_id": "local-signer",
    "network_type": "solana",
    "network": "testnet",
    "policies": {
      "allowed_programs": [
          "11111111111111111111111111111111",
          "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
          "BPFLoaderUpgradeab1e11111111111111111111111"
        ]
    }
  },
]
----

Available configuration fields
[cols="1,1,2"]
|===
|Field |Type |Description

|id
|String
|Unique id for the relayer

|name
|String
|Human readable name for the relayer

|paused
|Boolean
|Whether or not the relayer is paused (`true`, `false`)

|notification_id
|String
|ID of a configured notification object

|signer_id
|String
|ID of a configured signer

|network_type
|String
|Type of network the relayer will connect to (`evm`, `solana`)

|network
|String
|Network the relayer will connect to. Please refer to xref:supported_networks[`Supported networks`].

|policies
|list
|Overrides default policies. Please refer to the xref:network_policies[`Policies`] table
|===

[#supported_networks]
Supported networks
[cols="1,1, 2"]
|===
|Network type |Network |Description

|solana
|mainnet-beta
|Solana's mainnet

|solana
|devnet
|Solana's devnet

|solana
|testnet
|Solana's testnet
|===

[#network_policies]
Policies
[cols="1,1,1,2"]
|===
|Network type |Policy |Type |Description

|solana
|min_balance
|unsigned 64
|Minimum balance required for the relayer (in lamports). Optional.

|solana
|max_allowed_transfer_amount_lamports
|unsigned 64
|Maximum allowed transfer amount (in lamports) for a transaction. Optional.

|solana
|allowed_tokens
|Vector<AllowedToken>
|List of allowed tokens. Only these tokens are supported if provided. Optional.

|solana
|allowed_programs
|Vector<String>
|List of allowed programs by their identifiers. Only these programs are supported if provided.

|solana
|allowed_accounts
|Vector<String>
|List of allowed accounts by their public keys. The relayer will only operate with these accounts if provided.

|solana
|disallowed_accounts
|Vector<String>
|List of disallowed accounts by their public keys. These accounts will be explicitly blocked.

|solana
|max_tx_data_size
|unsigned 16
|Maximum transaction size. Optional.

|solana
|max_signatures
|unsigned 8
|Maximum supported signatures. Optional.
|===

Example for allowed_tokens:
[source,json]
----
"allowed_tokens": [
  {
    "mint": "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
    "max_allowed_fee": 1000000,
    "conversion_slippage_percentage": 1.0
  }
]
----

=== Key signers

These files should exist in `config/keys/`

== Important Considerations

CAUTION: This software is in alpha stage. Use in production environments at your own risk.

== Deployment Considerations

NOTE: The OpenZeppelin Relayer is designed to function as a backend service and is not meant to be directly exposed to the public internet. To protect the service from unauthorized access, deploy it behind your own secure backend infrastructure—such as a reverse proxy or firewall—and restrict access to trusted internal components only. Direct exposure can increase the risk of exploitation and security breaches.

== Support

For support or inquiries, contact defender-support@openzeppelin.com

== License
This project is licensed under the GNU Affero General Public License v3.0 - see the LICENSE file for details.

== Security
For security concerns, please refer to our link:https://github.com/OpenZeppelin/openzeppelin-relayer/blob/main/SECURITY.md[Security Policy].
