:relayer: https://github.com/OpenZeppelin/openzeppelin-relayer

= OpenZeppelin Relayer
:description: User guide for setting up and configuring OpenZeppelin Relayer.

OpenZeppelin Relayer is a service that provides infrastructure to relay transactions to the EVM & Non-EVM networks. It is designed to be used as a backend for dApps that need to interact with these networks.

**Features**

- Transaction relaying
- Transaction signing
- Transaction fee estimation
- Transaction gas estimation
- Transaction nonce management
- Transaction status monitoring
- Transaction history

**Supported Networks**

- EVM
- Solana

[NOTE]
====
To get started immediately, see xref:quickstart.adoc[Quickstart].
====

== Project Structure

The project follows a standard Rust project layout:


* `src/`: Source code
** Core implementation files
* `models/`: Data structures and types
** Type definitions and data models
* `repositories/`: Configuration storage
** Storage implementations
* `services/`: Core business logic
** Main service implementations
* `docs/`: Documentation
** User guides and API docs
* `scripts/`: Utility scripts
** Development and deployment helpers

For detailed information about each directory and its contents, see xref:structure.adoc[Project Structure Details].

== Getting Started

=== Prerequisites

* Rust 2021 edition
* Docker (optional, for containerized deployment)

=== Installation

==== Local Setup

. Clone the repository:

[source,bash]
----
git clone https://github.com/openzeppelin/openzeppelin-relayer
cd openzeppelin-relayer
----

. Install dependencies:

[source,bash]
----
cargo build
----

== Running the Relayer

=== Local Execution

[source,bash]
----
cargo run
----

=== Docker Deployment

The Relayer can be run as either a development or production container using the corresponding Dockerfile (`Dockerfile.development` or `Dockerfile.production`).

==== Environment Configuration

* Edit `.env` at the root of the repository to adjust environment variables
* The appropriate .env file will be included during image build

==== Building the Image

You can build using either standard Docker build or buildx:

[source,bash]
----
# Standard build
docker build --tag <your_image_tag> -f Dockerfile.<development | production> --squash-all

# Or using buildx
docker buildx build -f Dockerfile.<development | production> -t <name_of_image:tag> .
----

The build process will include:

* The appropriate .env file

==== Running the Container

You can use Docker Compose to run the container:

[source,bash]
----
docker-compose up
----

For production runs, you can use:

[source,bash]
----
DOCKERFILE=Dockerfile.production docker-compose up
----

== Configuration References

All configuration files should live under `./config`, including the signer configurations, under `./config/keys`.
Please ensure appropriate access permissions on all configuration files (for `./config/keys/*`, we recommend `0500`.

=== Main configuration file (config.json)

This file should exist in `config/config.json`

There are 3 important sections in this file:

* `signers` array, which must contain, at least, one valid signer configuration:
[source,json]
----
"signers": [
  {
    "id": "my_id",
    "type": "local",
    "path": "config/keys/local-signer.json",
    "passphrase": {
      "type": "plain",
      "value": "test"
    }
  }
]
----

Available configuration fields
[cols="1,1,2"]
|===
|Field |Type |Description

|id
|String
|Unique id for the signer

|type
|String
|Type of signer (see `supported signer types`)

|path
|String 
|path to the signer json file. Should be under the `./config` directory

|passphrase.type
|String
|Type of passphrase (`env` or `plain`)

|passphrase.value
|String
|Passphrase value, env variable name, ...
|===


* `notifications` array, which should contain, at least, one valid configuration:
[source,json]
----
"notifications": [
  {
    "id": "notification-test",
    "type": "webhook",
    "url": "https://webhook.site/f95cf78d-742d-4b21-88b7-d683e6fd147b",
    "signing_key": {
      "type": "env",
      "name": "WEBHOOK_SIGNING_KEY"
    }
  }
]
----
Available configuration fields
[cols="1,1,2"]
|===
|Field |Type |Description

|id
|String
|Unique id for the notification

|type
|String
|Type of notification (only `webhook` available, for now)

|url
|String
|Notification URL

|signing_key.type
|String
|Type of key used in signing the notification (`env` or `plain`)

|signing_key.name
|String
|Signing key value, env variable name, ...
|===

* `relayers` array, containing at least one valid relayer configuration:
[source,json]
----
"relayers": [
  {
    "id": "solana-testnet",
    "name": "Solana Testnet",
    "paused": false,
    "notification_id": "notification-test",
    "signer_id": "local-signer",
    "network_type": "solana",
    "network": "testnet",
    "policies": {
      "confirmation_blocks": 5
    }
  },
]
----

Available configuration fields
[cols="1,1,2"]
|===
|Field |Type |Description

|id
|String
|Unique id for the relayer

|name
|String
|Human readable name for the relayer

|paused
|Boolean
|Wether or not the relayer is paused (`true`, `false`)

|notification_id
|String
|ID of a configured notification object

|signer_id
|String
|ID of a configured signer

|network_type
|String
|Type of network the relayer will connect to (`evm`, `solana`)

|network
|String
|Network the relayer will connect to. Please refer to xref:supported_networks[`Supported networks`].

|policies
|list
|Overrides default policies. Please refer to the xref:network_policies[`Policies`] table
|===

[#supported_networks]
Supported networks
[cols="1,1, 2"]
|===
|Network type |Network |Description

|solana
|mainnet-beta
|Solana's mainnet

|solana
|devnet
|Solana's devnet

|solana
|testnet
|Solana's testnet
|===

[#network_policies]
Policies
[cols="1,1,1,2"]
|===
|Network type |Policy |Type |Description

|solana
|min_balance
|unsigned 64
|Minimum balance required for the relayer (in lamports).

|solana
|max_supported_token_fee
|unsigned 64
|Maximum supported token fee (in lamports) for a transaction. Optional.

|solana
|allowed_tokens
|Vector<String>
|List of allowed tokens by their identifiers. Only these tokens are supported if provided.

|solana
|allowed_programs
|Vector<String>
|List of allowed programs by their identifiers. Only these programs are supported if provided.

|solana
|allowed_accounts
|Vector<String>
|List of allowed accounts by their public keys. The relayer will only operate with these accounts if provided.

|solana
|disallowed_accounts
|Vector<String>
|List of disallowed accounts by their public keys. These accounts will be explicitly blocked.
|===

=== Key signers

These files should exist in `config/keys/`

== Important Considerations

CAUTION: This software is in alpha stage. Use in production environments at your own risk.

== Support

For support or inquiries, contact defender-support@openzeppelin.com

== License
This project is licensed under the GNU Affero General Public License v3.0 - see the LICENSE file for details.

== Security
For security concerns, please refer to our link:https://github.com/OpenZeppelin/openzeppelin-relayer/blob/main/SECURITY.md[Security Policy].
