= Quick Start Guide
:description: This guide provides step-by-step instructions for setting up OpenZeppelin Relayer. It includes prerequisites, installation, and configuration examples.

This guide provides step-by-step instructions for setting up OpenZeppelin Relayer. It includes prerequisites, installation, and configuration examples.

== Prerequisites

* Rust 2021 edition
* Redis
* Docker (optional, for containerized deployment)

== Environment Configuration

=== Configuration Instructions

. Clone the repository:
+
[source,bash]
----
git clone https://github.com/openzeppelin/openzeppelin-relayer
cd openzeppelin-relayer
----

. Modify the environment configuration file (`.env`) with your preferred verbosity level and set your API key:
+
Verbosity levels:

+
- Error
- Warn
- Info
- Debug
- Trace

+
[source,bash]
----
RUST_LOG=info
API_KEY=<enter your desired API key>
----

. Create a new signer key and save it under `config/keys`.
+
[source,bash]
----
cargo run --example create_key -- \
    --password DEFINE_YOUR_PASSWORD \
    --output-dir config/keys \
    --filename local-signer.json
----

. Create a configuration file for your relayer and save it in `config/config.json`.
+
You can find a sample config file in `config/config.example.json` or refer to xref:index.adoc#configuration_references[Configuration References] section.

+
[source,bash]
----
cp config/config.example.json config/config.json
----

+
NOTE: Make sure that, each of the `signers` definitions points to the right signer config file (the `path` property).

== Building and Deploying

=== Local Installation

. Install dependencies and build application:

+
[source,bash]
----
cargo build
----

. Run the built application:

+
[source,bash]
----
cargo run
----

=== Docker Installation

. Building and Running the docker image:

+
[source,bash]
----
docker compose up -d
----

+
By default docker compose command uses `Dockerfile.development` to build the image. If you want to use `Dockerfile.production`, you can use the following command:

+
[source,bash]
----
DOCKERFILE=Dockerfile.production docker compose up -d
----

== Using the relayer through the API

Please check our xref:api_reference.adoc[API guide] for a description and examples on using the Relayer.
