---
services:
  relayer:
    build:
      context: ../../
      dockerfile: Dockerfile.development
    secrets:
      - api_key
      - webhook_signing_key
      - keystore_passphrase
    ports:
      - 8080:8080/tcp
    environment:
      REDIS_URL: redis://redis:6379
      WEBHOOK_SIGNING_KEY: ${WEBHOOK_SIGNING_KEY}
      API_KEY: ${API_KEY}
      KEYSTORE_PASSPHRASE: ${KEYSTORE_PASSPHRASE}
      # Options: trace, debug, info, warn, error
      # Default: info
      LOG_LEVEL: ${LOG_LEVEL}
      # Options: stdout, file
      # Default: stdout
      LOG_MODE: ${LOG_MODE}
      # Set max log file size to rotate to new log file
      # Only used if LOG_MODE is file
      # Default: 1GB (1073741824 bytes)
      LOG_MAX_SIZE: ${LOG_MAX_SIZE}
    security_opt:
      - no-new-privileges
    networks:
      - relayer-network
      - metrics-network
    volumes:
      - ${CONFIG_DIR:-./config}:/app/config/:ro
      - ../../config/networks:/app/config/networks
      # Mount logs folder to persist logs
      - ${LOG_DATA_DIR:-./logs}:/app/logs
    depends_on:
      - redis
    restart: on-failure:5
  redis:
    image: redis:bookworm
    ports:
      - 6379:6379/tcp
    security_opt:
      - no-new-privileges
    volumes:
      - redis_data:/data
    command:
      - redis-server
      - --appendonly
      - 'yes'
      - --save
      - '60'
      - '1'
    networks:
      - relayer-network
      - metrics-network
    restart: on-failure:5
networks:
  metrics-network:
    internal: true
  relayer-network:
    driver: bridge
volumes:
  redis_data:
    driver: local
secrets:
  api_key:
    environment: API_KEY
  webhook_signing_key:
    environment: WEBHOOK_SIGNING_KEY
  keystore_passphrase:
    environment: KEYSTORE_PASSPHRASE
